import { Product } from '@/store/cart'

export const categories = [
  { id: 'electronics', name: 'Electronics', icon: '📱' },
  { id: 'fashion', name: 'Fashion', icon: '👕' },
  { id: 'home', name: 'Home & Garden', icon: '🏠' },
  { id: 'sports', name: 'Sports & Outdoors', icon: '⚽' },
  { id: 'books', name: 'Books', icon: '📚' },
  { id: 'beauty', name: 'Beauty & Health', icon: '💄' },
  { id: 'toys', name: 'Toys & Games', icon: '🎮' },
  { id: 'automotive', name: 'Automotive', icon: '🚗' },
]

export const products: Product[] = [
  // Electronics
  {
    id: '1',
    name: 'Wireless Noise-Cancelling Headphones',
    price: 299.99,
    originalPrice: 399.99,
    image: 'headphones-wireless-premium',
    category: 'electronics',
    description: 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and studio-quality sound.',
    rating: 4.8,
    reviews: 1247,
    inStock: true,
    sku: 'WH-1000XM5',
    tags: ['wireless', 'noise-cancelling', 'premium'],
  },
  {
    id: '2',
    name: 'Smart Watch Pro',
    price: 449.99,
    image: 'smartwatch-modern-black',
    category: 'electronics',
    description: 'Advanced fitness tracking, health monitoring, and smart notifications in a sleek design.',
    rating: 4.6,
    reviews: 892,
    inStock: true,
    sku: 'SW-PRO-2024',
    tags: ['smartwatch', 'fitness', 'health'],
  },
  {
    id: '3',
    name: 'Professional Camera Lens',
    price: 1299.99,
    originalPrice: 1499.99,
    image: 'camera-lens-professional',
    category: 'electronics',
    description: '85mm f/1.4 prime lens perfect for portraits and professional photography.',
    rating: 4.9,
    reviews: 341,
    inStock: true,
    sku: 'LENS-85F14',
    tags: ['photography', 'professional', 'portrait'],
  },

  // Fashion
  {
    id: '4',
    name: 'Premium Leather Jacket',
    price: 189.99,
    originalPrice: 249.99,
    image: 'leather-jacket-black-premium',
    category: 'fashion',
    description: 'Handcrafted genuine leather jacket with classic design and perfect fit.',
    rating: 4.7,
    reviews: 623,
    inStock: true,
    sku: 'LJ-PREM-BLK',
    tags: ['leather', 'jacket', 'premium'],
  },
  {
    id: '5',
    name: 'Designer Sneakers',
    price: 159.99,
    image: 'sneakers-white-designer',
    category: 'fashion',
    description: 'Limited edition designer sneakers with premium materials and comfort technology.',
    rating: 4.5,
    reviews: 1089,
    inStock: true,
    sku: 'SNK-DES-WHT',
    tags: ['sneakers', 'designer', 'limited'],
  },
  {
    id: '6',
    name: 'Luxury Silk Scarf',
    price: 89.99,
    originalPrice: 120.00,
    image: 'silk-scarf-luxury-pattern',
    category: 'fashion',
    description: '100% pure silk scarf with hand-painted floral design.',
    rating: 4.8,
    reviews: 267,
    inStock: true,
    sku: 'SCF-SILK-FLR',
    tags: ['silk', 'luxury', 'accessory'],
  },

  // Home & Garden
  {
    id: '7',
    name: 'Smart Home Security System',
    price: 399.99,
    originalPrice: 499.99,
    image: 'security-system-smart-home',
    category: 'home',
    description: 'Complete smart security system with cameras, sensors, and mobile app control.',
    rating: 4.6,
    reviews: 445,
    inStock: true,
    sku: 'SEC-SMART-PRO',
    tags: ['security', 'smart-home', 'safety'],
  },
  {
    id: '8',
    name: 'Ergonomic Office Chair',
    price: 349.99,
    image: 'office-chair-ergonomic-gray',
    category: 'home',
    description: 'Premium ergonomic office chair with lumbar support and adjustable features.',
    rating: 4.7,
    reviews: 721,
    inStock: true,
    sku: 'CHR-ERG-GRY',
    tags: ['office', 'ergonomic', 'furniture'],
  },
  {
    id: '9',
    name: 'Decorative Plant Set',
    price: 79.99,
    originalPrice: 99.99,
    image: 'plants-decorative-indoor',
    category: 'home',
    description: 'Beautiful set of 3 low-maintenance indoor plants perfect for any room.',
    rating: 4.4,
    reviews: 298,
    inStock: true,
    sku: 'PLT-SET-IND',
    tags: ['plants', 'decorative', 'indoor'],
  },

  // Sports & Outdoors
  {
    id: '10',
    name: 'Professional Yoga Mat',
    price: 69.99,
    originalPrice: 89.99,
    image: 'yoga-mat-professional-purple',
    category: 'sports',
    description: 'Non-slip professional yoga mat with alignment guides and carrying strap.',
    rating: 4.8,
    reviews: 1156,
    inStock: true,
    sku: 'YM-PRO-PRP',
    tags: ['yoga', 'fitness', 'mat'],
  },
  {
    id: '11',
    name: 'Camping Backpack 50L',
    price: 129.99,
    image: 'backpack-hiking-50l-green',
    category: 'sports',
    description: 'Durable 50L hiking backpack with multiple compartments and rain cover.',
    rating: 4.6,
    reviews: 673,
    inStock: true,
    sku: 'BP-HIK-50L',
    tags: ['hiking', 'camping', 'outdoor'],
  },
  {
    id: '12',
    name: 'Running Shoes Pro',
    price: 149.99,
    originalPrice: 199.99,
    image: 'running-shoes-professional-blue',
    category: 'sports',
    description: 'Professional running shoes with advanced cushioning and breathable design.',
    rating: 4.7,
    reviews: 934,
    inStock: true,
    sku: 'RS-PRO-BLU',
    tags: ['running', 'shoes', 'professional'],
  },

  // Beauty & Health
  {
    id: '13',
    name: 'Skincare Gift Set',
    price: 99.99,
    originalPrice: 139.99,
    image: 'skincare-set-premium-gift',
    category: 'beauty',
    description: 'Complete skincare routine with cleanser, serum, moisturizer, and sunscreen.',
    rating: 4.9,
    reviews: 412,
    inStock: true,
    sku: 'SKN-SET-GFT',
    tags: ['skincare', 'gift', 'premium'],
  },
  {
    id: '14',
    name: 'Massage Gun Pro',
    price: 199.99,
    image: 'massage-gun-professional',
    category: 'beauty',
    description: 'Professional-grade massage gun with multiple attachments and speed settings.',
    rating: 4.5,
    reviews: 578,
    inStock: true,
    sku: 'MG-PRO-BLK',
    tags: ['massage', 'recovery', 'professional'],
  },

  // Books
  {
    id: '15',
    name: 'Complete Web Development Guide',
    price: 49.99,
    originalPrice: 69.99,
    image: 'book-web-development-guide',
    category: 'books',
    description: 'Comprehensive guide to modern web development with practical examples.',
    rating: 4.8,
    reviews: 234,
    inStock: true,
    sku: 'BK-WEB-GDE',
    tags: ['programming', 'web-development', 'guide'],
  },
  {
    id: '16',
    name: 'Mindfulness & Meditation',
    price: 24.99,
    image: 'book-mindfulness-meditation',
    category: 'books',
    description: 'Practical guide to mindfulness and meditation for stress relief and mental clarity.',
    rating: 4.6,
    reviews: 456,
    inStock: true,
    sku: 'BK-MND-MED',
    tags: ['mindfulness', 'meditation', 'self-help'],
  },
]

// Featured products
export const featuredProducts = products.filter(product => 
  ['1', '4', '7', '10', '13'].includes(product.id)
)

// Sale products
export const saleProducts = products.filter(product => product.originalPrice)

// Top rated products
export const topRatedProducts = products
  .filter(product => product.rating && product.rating >= 4.7)
  .sort((a, b) => (b.rating || 0) - (a.rating || 0))

// Store information
export const storeInfo = {
  name: 'ModernShop',
  tagline: 'Premium products, modern experience',
  description: 'Discover a curated collection of premium products with exceptional quality and modern design.',
  contact: {
    email: 'hello@modernshop.com',
    phone: '+1 (555) 123-4567',
    address: '123 Commerce Street, City, State 12345',
  },
  social: {
    instagram: 'https://instagram.com/modernshop',
    twitter: 'https://twitter.com/modernshop',
    facebook: 'https://facebook.com/modernshop',
  },
  shipping: {
    freeThreshold: 75,
    standardRate: 9.99,
    expressRate: 19.99,
  },
  features: [
    'Free shipping on orders over $75',
    'Easy 30-day returns',
    'Secure payment processing',
    '24/7 customer support',
    'Quality guarantee',
  ],
}